Fixed Tutorial5.scala
Fixed the following error:
tutorial/Tutorial5.scala:78: error: value join is not a member of cascading.pipe.Pipe
possible cause: maybe a semicolon is missing before `value join'?
    .join('word -> 'dictWord, scores)
     ^